#ifndef CONTROLLINO_CONSTANTS_H
#define CONTROLLINO_CONSTANTS_H

#ifdef CONTROLLINO_MINI

const uint8_t CONTROLLINO_RELAYS[] = {
  CONTROLLINO_D0,
  CONTROLLINO_D1,
  CONTROLLINO_D2,
  CONTROLLINO_D3,
  CONTROLLINO_D4,
  CONTROLLINO_D5
};

const uint8_t CONTROLLINO_OUTPUTS[] = {
  CONTROLLINO_D0,
  CONTROLLINO_D1,
  CONTROLLINO_D2,
  CONTROLLINO_D3,
  CONTROLLINO_D4,
  CONTROLLINO_D5,
  CONTROLLINO_D6,
  CONTROLLINO_D7
};

const uint8_t CONTROLLINO_INPUTS[] = {
  CONTROLLINO_A0,
  CONTROLLINO_A1,
  CONTROLLINO_A2,
  CONTROLLINO_A3,
  CONTROLLINO_A4,
  CONTROLLINO_A5,
  CONTROLLINO_IN0,
  CONTROLLINO_IN1
};

#endif

#ifdef CONTROLLINO_MAXI

const uint8_t CONTROLLINO_RELAYS[] = {
  CONTROLLINO_R0,
  CONTROLLINO_R1,
  CONTROLLINO_R2,
  CONTROLLINO_R3,
  CONTROLLINO_R4,
  CONTROLLINO_R5,
  CONTROLLINO_R6,
  CONTROLLINO_R7,
  CONTROLLINO_R8,
  CONTROLLINO_R9
};

const uint8_t CONTROLLINO_OUTPUTS[] = {
  CONTROLLINO_D0,
  CONTROLLINO_D1,
  CONTROLLINO_D2,
  CONTROLLINO_D3,
  CONTROLLINO_D4,
  CONTROLLINO_D5,
  CONTROLLINO_D6,
  CONTROLLINO_D7,
  CONTROLLINO_D8,
  CONTROLLINO_D9,
  CONTROLLINO_D10,
  CONTROLLINO_D11
};

const uint8_t CONTROLLINO_INPUTS[] = {
  CONTROLLINO_A0,
  CONTROLLINO_A1,
  CONTROLLINO_A2,
  CONTROLLINO_A3,
  CONTROLLINO_A4,
  CONTROLLINO_A5,
  CONTROLLINO_A6,
  CONTROLLINO_A7,
  CONTROLLINO_A8,
  CONTROLLINO_A9,
  CONTROLLINO_IN0,
  CONTROLLINO_IN1
};

#endif

#ifdef CONTROLLINO_MEGA

const uint8_t CONTROLLINO_RELAYS[] = {
  CONTROLLINO_R0,
  CONTROLLINO_R1,
  CONTROLLINO_R2,
  CONTROLLINO_R3,
  CONTROLLINO_R4,
  CONTROLLINO_R5,
  CONTROLLINO_R6,
  CONTROLLINO_R7,
  CONTROLLINO_R8,
  CONTROLLINO_R9,
  CONTROLLINO_R10,
  CONTROLLINO_R11,
  CONTROLLINO_R12,
  CONTROLLINO_R13,
  CONTROLLINO_R14,
  CONTROLLINO_R15
};

const uint8_t CONTROLLINO_OUTPUTS[] = {
  CONTROLLINO_D0,
  CONTROLLINO_D1,
  CONTROLLINO_D2,
  CONTROLLINO_D3,
  CONTROLLINO_D4,
  CONTROLLINO_D5,
  CONTROLLINO_D6,
  CONTROLLINO_D7,
  CONTROLLINO_D8,
  CONTROLLINO_D9,
  CONTROLLINO_D10,
  CONTROLLINO_D11,
  CONTROLLINO_D12,
  CONTROLLINO_D13,
  CONTROLLINO_D14,
  CONTROLLINO_D15,
  CONTROLLINO_D16,
  CONTROLLINO_D17,
  CONTROLLINO_D18,
  CONTROLLINO_D19
};

const uint8_t CONTROLLINO_INPUTS[] = {
  CONTROLLINO_A0,
  CONTROLLINO_A1,
  CONTROLLINO_A2,
  CONTROLLINO_A3,
  CONTROLLINO_A4,
  CONTROLLINO_A5,
  CONTROLLINO_A6,
  CONTROLLINO_A7,
  CONTROLLINO_A8,
  CONTROLLINO_A9,
  CONTROLLINO_A10,
  CONTROLLINO_A11,
  CONTROLLINO_A12,
  CONTROLLINO_A13,
  CONTROLLINO_A14,
  CONTROLLINO_A15,
  CONTROLLINO_I16,
  CONTROLLINO_I17,
  CONTROLLINO_I18,
  CONTROLLINO_IN0,
  CONTROLLINO_IN1
};

#endif

const uint8_t CONTROLLINO_RELAYS_COUNT = sizeof(CONTROLLINO_RELAYS) / sizeof(CONTROLLINO_RELAYS[0]);
const uint8_t CONTROLLINO_INPUTS_COUNT = sizeof(CONTROLLINO_INPUTS) / sizeof(CONTROLLINO_INPUTS[0]);
const uint8_t CONTROLLINO_OUTPUTS_COUNT = sizeof(CONTROLLINO_OUTPUTS) / sizeof(CONTROLLINO_OUTPUTS[0]);

#define CONTROLLINO_R CONTROLLINO_RELAYS
#define CONTROLLINO_A CONTROLLINO_INPUTS
#define CONTROLLINO_D CONTROLLINO_OUTPUTS

#define CONTROLLINO_R_COUNT CONTROLLINO_RELAYS_COUNT
#define CONTROLLINO_A_COUNT CONTROLLINO_INPUTS_COUNT
#define CONTROLLINO_D_COUNT CONTROLLINO_OUTPUTS_COUNT
#endif
